// Keep STAGES in sync with config.js (Vercel-side)
export const config = {
  PROGRAM_ID: 'nyc-2026',
  BASE_URL: 'https://learning-challenge-legacy.vercel.app',
  EMAIL_FROM: 'noreply@griptape.org',
  AGE_MIN: 15,
  AGE_MAX: 19,
  ELIGIBLE_LOCATIONS: ['NYC', 'NJ'],
  PASSION_MIN_WORDS: 40,
  STIPEND_AMOUNT: 250,
  PROGRAM_DURATION_WEEKS: 8,
  MEETING_FREQUENCY_WEEKS: 2,
  TOKEN_BUFFER_HOURS: 24,
  DEFAULT_CHAMPION_CAPACITY: 3,
  FULL_SEND_TRIGGER_DAYS: 28,
  NOTIFY_DELAY_HOURS: 48,
  TEST_MODE: false,
  TERMINAL_STAGES: ['completed', 'rejected', 'removed'],
  STAGES: {
    submitted:           { next: 'screening',           deadline_days: null, nudge_days: [],     auto_remove: false, nudge_email: false, nudge_sms: false, notify_champion: false },
    screening:           { next: 'declaration_pending',  deadline_days: null, nudge_days: [],     auto_remove: false, nudge_email: false, nudge_sms: false, notify_champion: false },
    declaration_pending: { next: 'video_pending',         deadline_days: 10,   nudge_days: [6],    auto_remove: true,  nudge_email: true,  nudge_sms: true,  notify_champion: false },
    video_pending:       { next: 'video_review',          deadline_days: 10,   nudge_days: [5,9],  auto_remove: true,  nudge_email: true,  nudge_sms: true,  notify_champion: false },
    video_review:        { next: 'onboarding',            deadline_days: null, nudge_days: [],     auto_remove: false, nudge_email: false, nudge_sms: false, notify_champion: false },
    onboarding:          { next: 'mentor_pending',        deadline_days: null, nudge_days: [],     auto_remove: false, nudge_email: false, nudge_sms: false, notify_champion: false },
    mentor_pending:      { next: 'grant_pending',         deadline_days: 7,    nudge_days: [3,6],  auto_remove: true,  nudge_email: true,  nudge_sms: true,  notify_champion: true  },
    grant_pending:       { next: 'grant_review',          deadline_days: null, nudge_days: [5],    auto_remove: false, nudge_email: true,  nudge_sms: true,  notify_champion: false },
    grant_review:        { next: 'grant_approved',        deadline_days: null, nudge_days: [],     auto_remove: false, nudge_email: false, nudge_sms: false, notify_champion: false },
    grant_approved:      { next: 'final_video_pending',   deadline_days: null, nudge_days: [],     auto_remove: false, nudge_email: false, nudge_sms: false, notify_champion: false },
    final_video_pending: { next: 'full_send_review',      deadline_days: 14,   nudge_days: [7,12], auto_remove: true,  nudge_email: true,  nudge_sms: true,  notify_champion: false },
    full_send_review:    { next: 'completed',             deadline_days: null, nudge_days: [],     auto_remove: false, nudge_email: false, nudge_sms: false, notify_champion: false },
  },
  STAFF_EMAIL: Deno.env.get('STAFF_EMAIL') ?? '',
  RYAN_EMAIL:  Deno.env.get('RYAN_EMAIL')  ?? '',
  STATUS: {
    SUBMITTED:             'submitted',
    SCREENING:             'screening',
    DECLARATION_PENDING:   'declaration_pending',
    VIDEO_PENDING:         'video_pending',
    VIDEO_REVIEW:          'video_review',
    FLAGGED:               'flagged',
    ONBOARDING:            'onboarding',
    MENTOR_PENDING:        'mentor_pending',
    ORIENTATION_COMPLETE:  'orientation_complete',
    GRANT_PENDING:         'grant_pending',
    GRANT_REVIEW:          'grant_review',
    GRANT_APPROVED:        'grant_approved',
    ACTIVE:                'active',
    FINAL_VIDEO_PENDING:   'final_video_pending',
    FULL_SEND_REVIEW:      'full_send_review',
    COMPLETED:             'completed',
    REJECTED:              'rejected',
    REMOVED:               'removed',
  },
};
