// Keep STAGES in sync with config.js (Vercel-side)
export const config = {
  PROGRAM_ID: 'nyc-2026',
  BASE_URL: 'https://learning-challenge-legacy.vercel.app',
  EMAIL_FROM: 'noreply@griptape.org',
  AGE_MIN: 15,
  AGE_MAX: 19,
  ELIGIBLE_LOCATIONS: ['NYC', 'NJ'],
  PASSION_MIN_WORDS: 40,
  STIPEND_AMOUNT: 250,
  PROGRAM_DURATION_WEEKS: 8,
  MEETING_FREQUENCY_WEEKS: 2,
  TOKEN_BUFFER_HOURS: 24,
  TERMINAL_STAGES: ['completed', 'rejected', 'removed'],
  STAGES: {
    submitted:            { next: 'screening',            deadline_days: null, nudge_day: null, auto_remove: false },
    screening:            { next: 'declaration_pending',  deadline_days: null, nudge_day: null, auto_remove: false },
    declaration_pending:  { next: 'video_pending',        deadline_days: 60,   nudge_day: 7,    auto_remove: false },
    video_pending:        { next: 'video_review',         deadline_days: 10,   nudge_day: 7,    auto_remove: true  },
    video_review:         { next: 'onboarding',           deadline_days: null, nudge_day: null, auto_remove: false },
    onboarding:           { next: 'mentor_pending',       deadline_days: null, nudge_day: null, auto_remove: false },
    mentor_pending:       { next: 'grant_pending',        deadline_days: 14,   nudge_day: 10,   auto_remove: true  },
    orientation_complete: { next: 'grant_pending',        deadline_days: null, nudge_day: null, auto_remove: false },
    grant_pending:        { next: 'grant_review',         deadline_days: 14,   nudge_day: 10,   auto_remove: true  },
    grant_review:         { next: 'grant_approved',        deadline_days: null, nudge_day: null, auto_remove: false },
    grant_approved:       { next: 'active',               deadline_days: null, nudge_day: null, auto_remove: false },
    active:               { next: 'final_video_pending',  deadline_days: null, nudge_day: null, auto_remove: false },
    final_video_pending:  { next: 'showcase_invited',     deadline_days: 14,   nudge_day: 5,    auto_remove: false },
    showcase_invited:     { next: 'completed',            deadline_days: null, nudge_day: null, auto_remove: false },
  },
  STAFF_EMAIL: Deno.env.get('STAFF_EMAIL') ?? '',
  STATUS: {
    SUBMITTED:             'submitted',
    SCREENING:             'screening',
    DECLARATION_PENDING:   'declaration_pending',
    VIDEO_PENDING:         'video_pending',
    VIDEO_REVIEW:          'video_review',
    FLAGGED:               'flagged',
    ONBOARDING:            'onboarding',
    MENTOR_PENDING:        'mentor_pending',
    ORIENTATION_COMPLETE:  'orientation_complete',
    GRANT_PENDING:         'grant_pending',
    GRANT_REVIEW:          'grant_review',
    GRANT_APPROVED:        'grant_approved',
    ACTIVE:                'active',
    FINAL_VIDEO_PENDING:   'final_video_pending',
    SHOWCASE_INVITED:      'showcase_invited',
    COMPLETED:             'completed',
    REJECTED:              'rejected',
    REMOVED:               'removed',
  },
};
