export const config = {
  PROGRAM_ID: 'nyc-2026',
  BASE_URL: 'https://learning-challenge-legacy.vercel.app',
  EMAIL_FROM: 'noreply@griptape.org',
  AGE_MIN: 15,
  AGE_MAX: 19,
  ELIGIBLE_LOCATIONS: ['NYC', 'NJ'],
  PASSION_MIN_WORDS: 40,
  STIPEND_AMOUNT: 250,
  PROGRAM_DURATION_WEEKS: 10,
  MEETING_FREQUENCY_WEEKS: 2,
  DEFAULT_CHAMPION_CAPACITY: 3,
  TOKEN_BUFFER_HOURS: 24,
  TERMINAL_STAGES: ['completed', 'rejected', 'removed'],
  STAGES: {
    submitted:           { next: 'screening',          deadline_days: null, nudge_day: null, auto_remove: false },
    screening:           { next: 'declaration_pending', deadline_days: null, nudge_day: null, auto_remove: false },
    declaration_pending: { next: 'video_pending',        deadline_days: 60,   nudge_day: 7,    auto_remove: false },
    // generating_video_token — intermediate lock used by process-declaration advance_status() (not a full stage)
    video_pending:       { next: 'video_review',        deadline_days: 10,   nudge_day: 7,    auto_remove: true  },
    // video_review — also used as intermediate lock by validate-video advance_status() before accepting/rejecting
    video_review:        { next: 'onboarding',          deadline_days: null, nudge_day: null, auto_remove: false },
    onboarding:          { next: 'mentor_pending',      deadline_days: null, nudge_day: null, auto_remove: false },
    mentor_pending:      { next: 'grant_pending',       deadline_days: 14,   nudge_day: 10,   auto_remove: true  },
    grant_pending:       { next: 'grant_review',        deadline_days: 14,   nudge_day: 10,   auto_remove: true  },
    grant_review:        { next: 'active',              deadline_days: null, nudge_day: null, auto_remove: false },
    active:              { next: 'final_video_pending', deadline_days: null, nudge_day: null, auto_remove: false },
    final_video_pending: { next: 'showcase_invited',    deadline_days: 14,   nudge_day: 5,    auto_remove: false },
    showcase_invited:    { next: 'completed',           deadline_days: null, nudge_day: null, auto_remove: false },
  },
};
